/// ============================================================
/// RunModel — Supabase PostgreSQL serialization
///
/// Table: `runs`
/// Primary key: `id` (UUID, auto-generated by Supabase default)
/// `polyline_coords` stored as JSONB array for spatial data.
/// ============================================================

import 'dart:convert';

class RunModel {
  final String? id;
  final String userId;
  final DateTime timestamp;
  final double distanceKm;
  final int durationSeconds;
  final String primarySector;
  final int pointsEarned;
  final List<Map<String, double>> polylineCoords;

  const RunModel({
    this.id,
    required this.userId,
    required this.timestamp,
    required this.distanceKm,
    required this.durationSeconds,
    required this.primarySector,
    required this.pointsEarned,
    required this.polylineCoords,
  });

  /// Deserialize from Supabase row.
  factory RunModel.fromMap(Map<String, dynamic> data) {
    List<Map<String, double>> coords = [];
    if (data['polyline_coords'] != null) {
      final field = data['polyline_coords'];
      // Realtime payloads can deliver JSONB as a String; REST gives a List.
      final raw = (field is String ? json.decode(field) : field) as List<dynamic>;
      coords = raw.map((e) {
        if (e is Map) {
          return {
            'lat': ((e['lat'] ?? 0) as num).toDouble(),
            'lng': ((e['lng'] ?? 0) as num).toDouble(),
          };
        }
        return {'lat': 0.0, 'lng': 0.0};
      }).toList();
    }

    return RunModel(
      id: data['id'] as String?,
      userId: (data['user_id'] as String?) ?? '',
      timestamp: DateTime.tryParse(data['timestamp']?.toString() ?? '') ?? DateTime.now(),
      distanceKm: ((data['distance_km'] ?? 0) as num).toDouble(),
      durationSeconds: (data['duration_seconds'] ?? 0) as int,
      primarySector: (data['primary_sector'] as String?) ?? '',
      pointsEarned: (data['points_earned'] ?? 0) as int,
      polylineCoords: coords,
    );
  }

  /// Serialize for INSERT. id is auto-generated by Supabase.
  Map<String, dynamic> toInsertMap() {
    return {
      'user_id': userId,
      'timestamp': timestamp.toUtc().toIso8601String(),
      'distance_km': distanceKm,
      'duration_seconds': durationSeconds,
      'primary_sector': primarySector,
      'points_earned': pointsEarned,
      'polyline_coords': polylineCoords,
    };
  }
}
